kind: verify-report
metadata:
    tool:
        verifier-version: 1.13.13
        profile:
            VendorType: redhat
            version: v1.3
        reportDigest: uint64:1264853845255763448
        chart-uri: /charts/0.10.0/src
        digests:
            chart: sha256:92e4ec65eb510e7733b648d93da525048d754a652206586b40449343a33832b7
        lastCertifiedTimestamp: "2025-11-03T09:12:15.089949+00:00"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: '>=4.1'
        webCatalogOnly: false
    chart:
        name: flightctl
        home: https://github.com/flightctl/flightctl
        sources: []
        version: 0.1.0
        description: A helm chart for flightctl
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: latest
        deprecated: false
        annotations:
            charts.openshift.io/archs: x86_64
            charts.openshift.io/name: RHEM
            charts.openshift.io/provider: RedHat
            charts.openshift.io/supportURL: https://github.com/flightctl/flightctl
        kubeversion: '>= 1.13.0'
        dependencies:
            - name: keycloak
              version: 0.0.1
              repository: ""
            - name: ui
              version: 0.0.1
              repository: ""
              condition: ui.enabled
        type: application
    chart-overrides: ""
results:
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: test
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: test
